#!/usr/bin/bash


if [ "$#" -ne 1 ]; then
		echo "Usage: run <path/to/submission>"
		exit
fi

ExNum=5


ScriptDir=/cs/course/current/labcc2/presubmit/ex${ExNum}/prsb

python3 -u ${ScriptDir} "$1" nogit 2>&1 
